update to custom linter action

diff --git a/.github/workflows/CUSTOM_LINTS.yml b/.github/workflows/CUSTOM_LINTS.yml
--- a/.github/workflows/CUSTOM_LINTS.yml
+++ b/.github/workflows/CUSTOM_LINTS.yml
@@ -12,10 +12,9 @@ on:
   workflow_dispatch:
     branches: [main, dev]
   push:
-    branches: [main, dev]
+    branches: [main]
 
-permissions:
-  contents: read
+permissions: read-all
 
 jobs:
   goodpractice_check:
@@ -38,7 +37,7 @@ jobs:
           Rscript -e "devtools::install()"
       - name: run tests
         run: |
-           Rscript -e "g <- goodpractice::gp(system.file(package = "Colossus"), checks = goodpractice::all_checks()[c(1:17,19,21:23,25:35,37:326,328:338)])
+           Rscript -e "g <- goodpractice::gp(".", checks = goodpractice::all_checks()[c(1:17,19,21:23,25:35,37:326,328:338)])
            print(g)
            if (length(goodpractice::failed_check(g)) == 0){
              stop("Failed checks")
@@ -47,56 +46,40 @@ jobs:
   cpplint_check:
     runs-on: ubuntu-latest
     steps:
-      - name: install libraries
-        run: |
-          sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libuv1-dev cpplint
-      - name: run tests
-        run: |
-               cpplint --filter=-whitespace/line_length,-readability/fn_size,-runtime/references --exclude=src/RcppExports.* --exclude=src/*.*o --exclude=src/Makevars* src/*.* &> cpplint_out.txt
-                if grep -q 'Total errors found:' cpplint_out.txt; then
-                    echo "cpplint error"
-                    exit 1
-                fi
+    - uses: actions/checkout@v4
+    - run: |
+        pipx run cpplint --filter=-whitespace/line_length,-readability/fn_size,-runtime/references --exclude=src/RcppExports.* --exclude=src/*.*o --exclude=src/Makevars* src/*.* &> cpplint_out.txt
+        if grep -q 'Total errors found:' cpplint_out.txt; then
+            echo "cpplint error"
+            exit 1
+        fi
   cppcheck_check:
     runs-on: ubuntu-latest
     steps:
-      - name: install libraries
-        run: |
-          sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libuv1-dev cppcheck
-      - name: run tests
-        run: |
-               cppcheck -i src/RcppExports.cpp --enable=warning,portability,performance --error-exitcode=1 --inline-suppr src &> cppcheck_out.txt
-                if grep -q ']' cppcheck_out.txt; then
-                    echo "cppcheck error"
-                    exit 1
-                fi
+    - uses: actions/checkout@v4
+    - run: |
+        pipx run cppcheck -i src/RcppExports.cpp --enable=warning,portability,performance --error-exitcode=1 --inline-suppr src &> cppcheck_out.txt
+        if grep -q ']' cppcheck_out.txt; then
+            echo "cppcheck error"
+            exit 1
+        fi
   lintr:
     name: Run lintr scanning
     runs-on: ubuntu-latest
-    permissions:
-      contents: read # for checkout to fetch code
-      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
-      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
-
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v6
 
-      - name: Setup R
-        uses: r-lib/actions/setup-r@4e1feaf90520ec1215d1882fdddfe3411c08e492
+      - uses: r-lib/actions/setup-r@v2
 
-      - name: Setup lintr
-        uses: r-lib/actions/setup-r-dependencies@4e1feaf90520ec1215d1882fdddfe3411c08e492
+      - uses: r-lib/actions/setup-r-dependencies@v2
         with:
-          extra-packages: lintr
+          extra-packages: any::lintr, local::.
+          needs: lint
 
-      - name: Run lintr
-        run: lintr::sarif_output(lintr::lint_dir("."), "lintr-results.sarif")
+      - name: Lint
+        run: lintr::lint_package()
         shell: Rscript {0}
-        continue-on-error: true
-
-      - name: Upload analysis results to GitHub
-        uses: github/codeql-action/upload-sarif@v3
-        with:
-          sarif_file: lintr-results.sarif
-          wait-for-processing: true
+        env:
+          LINTR_ERROR_ON_LINT: true
